package com.smartdeviceny.njts.values;

public interface Config {
    String FAVORITES = "favorites";

    String START_STATION = "CONFIG_START_STATION";
    String STOP_STATION = "CONFIG_STOP_STATION";
    String ROUTE = "CONFIG_ROUTE";
    String DELTA_DAYS = "CONFIG_DELTA_DAYS";
    String DV_STATION = "CONFIG_DV_STATION";

    String POLLING_TIME = "CONFIG_POLLING_TIME_NEW_ENTRY";
    String ALERT_POLLING_TIME = "CONFIG_ALERT_POLLING_TIME_NEW_ENTRY";

    String DEBUG = "CONFIG_DEBUG";
    String TRAIN_NOTIFICTION = "CONFIG_TRAIN_NOTIFICTION";
    String NOTIFICATION_DELAY="CONFIG_NOTIFICATION_DELAY";

    String UPDATE_LAST_CHECK_TIME = "CONFIG_UPDATE_LAST_CHECK_TIME";
    String DEPARTURE_VISION = "CONFIG_DEPARTURE_VISION";
    String DEPARTURE_VISION_HISTORY = "CONFIG_DEPARTURE_VISION_HISTORY";
    String LAST_UPDATE_CHECK = "CONFIG_LAST_UPDATE_CHECK";
    String LAST_ALERT_TIME = "CONFIG_LAST_ALERT_TIME";
    String ALERT_JSON = "CONFIG_ALERT_JSON";

    String EXPERMENTAL_FEATURES="EXPERMENTAL_FEATURES";

}
